extension=couchbase.so

; Configuration
couchbase.log_level = 'TRACE'
;couchbase.encoder.format = 'json'
;couchbase.encoder.compression = 'off'
;couchbase.encoder.compression_threshold = 0
;couchbase.encoder.compression_factor = 0.0
;couchbase.decoder.json_arrays = 1
;couchbase.pool.max_idle_time_sec = 60
;couchbase.allow_fallback_to_bucket_connection = 0
